<?php

function retrofit_fixtures_menu()
{
    return [
        'retrofit/drupal_add_library' => [
            'title' => 'drupal_add_library',
            'page callback' => 'retrofit_fixtures_drupal_add_library',
            'access callback' => TRUE,
        ],
        'retrofit/drupal_add_js_setting' => [
            'title' => 'drupal_add_js',
            'page callback' => 'retrofit_fixtures_drupal_add_js_setting',
            'access callback' => TRUE,
        ],
        'retrofit/attached_js_setting' => [
            'title' => 'drupal js settings',
            'page callback' => 'retrofit_fixtures_attached_js_setting',
            'access callback' => TRUE,
        ],
        'retrofit/drupal_set_title' => [
            'title' => 'this title will be overridden',
            'page callback' => 'retrofit_fixtures_drupal_set_title',
            'access callback' => TRUE,
        ],
    ];
}

function retrofit_fixtures_drupal_add_library()
{
    drupal_add_library('system', 'jquery');
    return 'drupal_add_library page';
}

function retrofit_fixtures_drupal_add_js_setting()
{
    drupal_add_js(['hello' => 'World'], ['type' => 'setting']);
    return 'drupal_add_js page';
}

function retrofit_fixtures_attached_js_setting()
{
    return [
        '#attached' => [
            'js' => [
                [
                    'type' => 'setting',
                    'data' => ['hello' => 'World']
                ]
            ],
        ],
        'hello' => [
            '#plain_text' => '#attached Drupal.settings'
        ]
    ];
}

function retrofit_fixtures_process_html(&$variables)
{
    $variables['attributes']['hook_process'] = __FUNCTION__;
}

function retrofit_fixtures_drupal_set_title()
{
    drupal_set_title('this title has been overridden');
    return 'drupal_set_title page';
}
