<?php

const COMMENT_NOT_PUBLISHED = 0;

const COMMENT_PUBLISHED = 1;

const COMMENT_MODE_FLAT = 0;

const COMMENT_MODE_THREADED = 1;

const COMMENT_ANONYMOUS_MAYNOT_CONTACT = 0;

const COMMENT_ANONYMOUS_MAY_CONTACT = 1;

const COMMENT_ANONYMOUS_MUST_CONTACT = 2;

const COMMENT_FORM_SEPARATE_PAGE = 0;

const COMMENT_FORM_BELOW = 1;

const COMMENT_NODE_HIDDEN = 0;

const COMMENT_NODE_CLOSED = 1;

const COMMENT_NODE_OPEN = 2;
